GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Monquavious",
    "number": "02-942555"
}

###
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6875b91440546943d2b259dc